
-- Add home-only and away-only rolling stat columns to team_rolling_stats
ALTER TABLE public.team_rolling_stats
  ADD COLUMN IF NOT EXISTS home_matches_used integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_goals_scored numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_goals_conceded numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_total_goals numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_over_25_goals_pct integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_btts_pct integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_corners_for numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_corners_against numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_total_corners numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_over_95_corners_pct integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_cards_for numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_cards_against numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_avg_total_cards numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_over_35_cards_pct integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_matches_used integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_goals_scored numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_goals_conceded numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_total_goals numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_over_25_goals_pct integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_btts_pct integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_corners_for numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_corners_against numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_total_corners numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_over_95_corners_pct integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_cards_for numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_cards_against numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_avg_total_cards numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_over_35_cards_pct integer DEFAULT 0;
