-- Add comprehensive statistics columns to ml_training_data
ALTER TABLE public.ml_training_data 
ADD COLUMN IF NOT EXISTS home_xg numeric DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_xg numeric DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_shots_on_goal integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_shots_on_goal integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_shots_off_goal integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_shots_off_goal integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_total_shots integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_total_shots integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_blocked_shots integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_blocked_shots integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_shots_insidebox integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_shots_insidebox integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_shots_outsidebox integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_shots_outsidebox integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_fouls integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_fouls integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_corners integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_corners integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_offsides integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_offsides integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_possession text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_possession text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_yellow_cards integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_yellow_cards integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_red_cards integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_red_cards integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_goalkeeper_saves integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_goalkeeper_saves integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_total_passes integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_total_passes integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_passes_accurate integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_passes_accurate integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_passes_pct text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS away_passes_pct text DEFAULT NULL;

-- Add index for xG analysis
CREATE INDEX IF NOT EXISTS idx_ml_training_xg ON public.ml_training_data(home_xg, away_xg) WHERE home_xg IS NOT NULL;